export type LanguageCode = 'vi' | 'en';

export const translations = {
  vi: {
    common: { cancel: 'Hủy', save: 'Lưu', saving: 'Đang lưu...', loading: 'Đang tải...', home: 'Trang chủ', reply: 'Trả lời', post: 'Đăng' },
    header: { searchPlaceholder: 'Tìm kiếm tài khoản và video', upload: 'Tải lên', login: 'Đăng nhập', logout: 'Đăng xuất', profile: 'Trang cá nhân' },
    sidebar: { forYou: 'Đề xuất', explore: 'Khám phá', following: 'Đã follow', friends: 'Bạn bè', messages: 'Tin nhắn', activity: 'Hoạt động', upload: 'Tải lên', profile: 'Hồ sơ', more: 'Thêm', settings: 'Cài đặt', general: 'Chung', language: 'Ngôn ngữ', darkMode: 'Chế độ tối', support: 'Hỗ trợ', other: 'Khác', followedAccounts: 'Các tài khoản đã follow', seeAll: 'Xem tất cả', guestPrompt: 'Đăng nhập để follow các nhà sáng tạo, thích video và xem bình luận.', about: 'Giới thiệu', contact: 'Liên hệ', report: 'Báo cáo', terms: 'Điều khoản' },
    profile: { edit: 'Sửa hồ sơ', displayName: 'Tên hiển thị', bio: 'Tiểu sử', birthday: 'Ngày sinh', gender: 'Giới tính', genderOther: 'Khác', genderMale: 'Nam', genderFemale: 'Nữ', avatar: 'Ảnh đại diện', chooseImage: 'Chọn ảnh', zoom: 'Thu phóng', horizontal: 'Vị trí ngang', vertical: 'Vị trí dọc', noBio: 'Chưa có tiểu sử.', noVideos: 'Chưa có video nào', private: 'Riêng tư', videos: 'Video', updateSuccess: 'Đã cập nhật hồ sơ', updateFailed: 'Không thể cập nhật hồ sơ', requiredName: 'Tên hiển thị cần từ 3 đến 100 ký tự', invalidImage: 'Chỉ hỗ trợ ảnh JPEG, PNG hoặc WebP', imageTooLarge: 'Ảnh phải nhỏ hơn 8 MB', notFound: 'Không tìm thấy tài khoản', notFoundDescription: 'Người dùng này không tồn tại hoặc đã bị khóa.', following: 'Đang follow', followers: 'Follower', likes: 'Lượt thích' },
    search: { title: 'Tìm kiếm', top: 'Top', accounts: 'Người dùng', videos: 'Video', images: 'Ảnh', empty: 'Không tìm thấy kết quả phù hợp.', hint: 'Nhập từ khóa để tìm tài khoản hoặc video.' },
    video: { noComments: 'Chưa có bình luận nào', firstComment: 'Hãy là người đầu tiên bình luận về video này!', addComment: 'Thêm bình luận...', replyingTo: 'Đang trả lời', viewReplies: 'Xem {{count}} câu trả lời', hideReplies: 'Ẩn câu trả lời', repliesFailed: 'Không thể tải câu trả lời', copyLink: 'Đã sao chép liên kết video!', copyLinkTitle: 'Sao chép liên kết', notFound: 'Video không tồn tại', sound: 'nhạc nền', save: 'Lưu', user: 'Người dùng', commentFailed: 'Không thể gửi bình luận' },
    auth: { loginTitle: 'Đăng nhập vào TikTok', signupTitle: 'Đăng ký tài khoản', loginDescription: 'Tiếp tục xem, chia sẻ và kết nối với mọi người.', signupDescription: 'Tạo tài khoản để đăng tải video và theo dõi nhà sáng tạo.', displayName: 'Tên hiển thị', displayNamePlaceholder: 'Tên của bạn', username: 'Tên người dùng', usernameHint: 'Chỉ sử dụng chữ cái, số, dấu chấm hoặc dấu gạch dưới.', password: 'Mật khẩu', passwordPlaceholder: 'Nhập mật khẩu của bạn', passwordCreatePlaceholder: 'Tối thiểu 8 ký tự', login: 'Đăng nhập', signup: 'Đăng ký tài khoản', switchSignup: 'Bạn chưa có tài khoản?', switchLogin: 'Bạn đã có tài khoản?', orGoogle: 'Hoặc tiếp tục với' },
    upload: { authRequired: 'Yêu cầu đăng nhập', authDescription: 'Vui lòng đăng nhập để tải video lên. Đang chuyển hướng...', invalidFile: 'Chỉ hỗ trợ tệp video MP4 hoặc WebM.', tooLarge: 'Video vượt quá giới hạn 100 MB.', failed: 'Có lỗi xảy ra trong quá trình tải lên.', title: 'Tải video lên', subtitle: 'Đăng video lên tài khoản của bạn', success: 'Đăng video thành công! Đang chuyển về trang cá nhân...', choose: 'Chọn video để tải lên', drop: 'Hoặc kéo và thả tệp tại đây', format: 'Định dạng: MP4, WebM', maxSize: 'Dung lượng: Tối đa 100 MB', maxDuration: 'Độ dài: Dưới 3 phút', chooseFile: 'Chọn tệp', chooseAgain: 'Hủy và chọn lại', caption: 'Chú thích', captionPlaceholder: 'Viết chú thích cho video. Dùng # để thêm hashtag', visibility: 'Ai có thể xem video này', public: 'Mọi người (Công khai)', friends: 'Bạn bè', private: 'Chỉ mình tôi (Riêng tư)', permissions: 'Cho phép người dùng', comments: 'Bình luận', download: 'Tải xuống', duration: 'Thời lượng', dimensions: 'Kích thước', size: 'Dung lượng', requesting: 'Đang chuẩn bị phiên tải lên...', uploading: 'Đang gửi video đến kho lưu trữ...', saving: 'Đang xuất bản video...', processing: 'Đang xử lý...' },
    misc: { share: 'Chia sẻ', loadingVideos: 'Đang tải video...', comingSoon: 'Tính năng này sẽ được triển khai sau.', liveSoon: 'Tính năng Live sẽ được triển khai sau.' },
  },
  en: {
    common: { cancel: 'Cancel', save: 'Save', saving: 'Saving...', loading: 'Loading...', home: 'Home', reply: 'Reply', post: 'Post' },
    header: { searchPlaceholder: 'Search accounts and videos', upload: 'Upload', login: 'Log in', logout: 'Log out', profile: 'View profile' },
    sidebar: { forYou: 'For You', explore: 'Explore', following: 'Following', friends: 'Friends', messages: 'Messages', activity: 'Activity', upload: 'Upload', profile: 'Profile', more: 'More', settings: 'Settings', general: 'General', language: 'Language', darkMode: 'Dark mode', support: 'Support', other: 'Other', followedAccounts: 'Following accounts', seeAll: 'See all', guestPrompt: 'Log in to follow creators, like videos, and view comments.', about: 'About', contact: 'Contact', report: 'Report', terms: 'Terms' },
    profile: { edit: 'Edit profile', displayName: 'Display name', bio: 'Bio', birthday: 'Birthday', gender: 'Gender', genderOther: 'Other', genderMale: 'Male', genderFemale: 'Female', avatar: 'Profile photo', chooseImage: 'Choose image', zoom: 'Zoom', horizontal: 'Horizontal position', vertical: 'Vertical position', noBio: 'No bio yet.', noVideos: 'No videos yet', private: 'Private', videos: 'Videos', updateSuccess: 'Profile updated', updateFailed: 'Could not update profile', requiredName: 'Display name must contain 3–100 characters', invalidImage: 'Only JPEG, PNG, or WebP images are supported', imageTooLarge: 'Image must be smaller than 8 MB', notFound: 'Account not found', notFoundDescription: 'This user does not exist or has been suspended.', following: 'Following', followers: 'Followers', likes: 'Likes' },
    search: { title: 'Search', top: 'Top', accounts: 'Users', videos: 'Videos', images: 'Images', empty: 'No matching results.', hint: 'Enter a keyword to find accounts or videos.' },
    video: { noComments: 'No comments yet', firstComment: 'Be the first to comment on this video.', addComment: 'Add comment...', replyingTo: 'Replying to', viewReplies: 'View {{count}} replies', hideReplies: 'Hide replies', repliesFailed: 'Could not load replies', copyLink: 'Video link copied.', copyLinkTitle: 'Copy link', notFound: 'Video not found', sound: 'original sound', save: 'Save', user: 'User', commentFailed: 'Could not post comment' },
    auth: { loginTitle: 'Log in to TikTok', signupTitle: 'Create an account', loginDescription: 'Keep watching, sharing, and connecting with others.', signupDescription: 'Create an account to upload videos and follow creators.', displayName: 'Display name', displayNamePlaceholder: 'Your name', username: 'Username', usernameHint: 'Use letters, numbers, periods, or underscores only.', password: 'Password', passwordPlaceholder: 'Enter your password', passwordCreatePlaceholder: 'At least 8 characters', login: 'Log in', signup: 'Create account', switchSignup: "Don't have an account?", switchLogin: 'Already have an account?', orGoogle: 'Or continue with' },
    upload: { authRequired: 'Login required', authDescription: 'Please log in to upload a video. Redirecting...', invalidFile: 'Only MP4 or WebM video files are supported.', tooLarge: 'Video exceeds the 100 MB limit.', failed: 'The upload could not be completed.', title: 'Upload video', subtitle: 'Post a video to your account', success: 'Video posted. Redirecting to your profile...', choose: 'Choose a video to upload', drop: 'Or drag and drop a file here', format: 'Format: MP4, WebM', maxSize: 'Size: Up to 100 MB', maxDuration: 'Length: Under 3 minutes', chooseFile: 'Choose file', chooseAgain: 'Cancel and choose again', caption: 'Caption', captionPlaceholder: 'Write a caption. Use # to add hashtags', visibility: 'Who can watch this video', public: 'Everyone (Public)', friends: 'Friends', private: 'Only me (Private)', permissions: 'Allow viewers to', comments: 'Comment', download: 'Download', duration: 'Duration', dimensions: 'Dimensions', size: 'Size', requesting: 'Preparing upload...', uploading: 'Uploading to object storage...', saving: 'Publishing video...', processing: 'Processing...' },
    misc: { share: 'Share', loadingVideos: 'Loading videos...', comingSoon: 'This feature will be available in a future update.', liveSoon: 'Live will be available in a future update.' },
  },
} as const;
