/**
 * Centralized message code constants for i18n support.
 *
 * Backend returns these codes in the `messageCode` field.
 * Frontend maps each code to a localized display string.
 *
 * Convention: <MODULE>_<ACTION/DESCRIPTION> in UPPER_SNAKE_CASE
 */
export enum MessageCode {
  // ==================== Auth ====================
  AUTH_EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  AUTH_USERNAME_EXISTS = 'AUTH_USERNAME_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_INVALID_GOOGLE_TOKEN = 'AUTH_INVALID_GOOGLE_TOKEN',
  AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS',

  // ==================== User ====================
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_NOT_ACTIVE = 'USER_NOT_ACTIVE',
  USER_CANNOT_FOLLOW_SELF = 'USER_CANNOT_FOLLOW_SELF',
  USER_ALREADY_FOLLOWED = 'USER_ALREADY_FOLLOWED',
  USER_NOT_FOLLOWED = 'USER_NOT_FOLLOWED',
  USER_FOLLOWED = 'USER_FOLLOWED',
  USER_UNFOLLOWED = 'USER_UNFOLLOWED',

  // ==================== Storage ====================
  STORAGE_CONFIG_MISSING = 'STORAGE_CONFIG_MISSING',

  // ==================== Video ====================
  VIDEO_NOT_FOUND = 'VIDEO_NOT_FOUND',
  VIDEO_FORBIDDEN = 'VIDEO_FORBIDDEN',
  VIDEO_DELETED = 'VIDEO_DELETED',
  VIDEO_VIEW_RECORDED = 'VIDEO_VIEW_RECORDED',

  // ==================== Interaction ====================
  VIDEO_ALREADY_LIKED = 'VIDEO_ALREADY_LIKED',
  VIDEO_NOT_LIKED = 'VIDEO_NOT_LIKED',
  VIDEO_LIKED = 'VIDEO_LIKED',
  VIDEO_UNLIKED = 'VIDEO_UNLIKED',
  VIDEO_ALREADY_BOOKMARKED = 'VIDEO_ALREADY_BOOKMARKED',
  VIDEO_NOT_BOOKMARKED = 'VIDEO_NOT_BOOKMARKED',
  VIDEO_BOOKMARKED = 'VIDEO_BOOKMARKED',
  VIDEO_BOOKMARK_REMOVED = 'VIDEO_BOOKMARK_REMOVED',

  // ==================== Comment ====================
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_FORBIDDEN = 'COMMENT_FORBIDDEN',
  COMMENT_DISABLED = 'COMMENT_DISABLED',
  COMMENT_RATE_LIMITED = 'COMMENT_RATE_LIMITED',
  COMMENT_CREATED = 'COMMENT_CREATED',
  COMMENT_DELETED = 'COMMENT_DELETED',

  // ==================== Sound ====================
  SOUND_NOT_FOUND = 'SOUND_NOT_FOUND',

  // ==================== Hashtag ====================
  HASHTAG_NOT_FOUND = 'HASHTAG_NOT_FOUND',
}
