/**
 * Centralized message code constants for i18n support.
 *
 * Backend returns these codes in the `messageCode` field.
 * Frontend maps each code to a localized display string.
 *
 * Convention: <MODULE>_<ACTION/DESCRIPTION> in UPPER_SNAKE_CASE
 */
export enum MessageCode {
  // ==================== Auth ====================
  AUTH_EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  AUTH_USERNAME_EXISTS = 'AUTH_USERNAME_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_INVALID_GOOGLE_TOKEN = 'AUTH_INVALID_GOOGLE_TOKEN',
  AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS',

  // ==================== User ====================
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_NOT_ACTIVE = 'USER_NOT_ACTIVE',
  USER_CANNOT_FOLLOW_SELF = 'USER_CANNOT_FOLLOW_SELF',
  USER_ALREADY_FOLLOWED = 'USER_ALREADY_FOLLOWED',
  USER_NOT_FOLLOWED = 'USER_NOT_FOLLOWED',
  USER_FOLLOWED = 'USER_FOLLOWED',
  USER_UNFOLLOWED = 'USER_UNFOLLOWED',
}
